apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app-demo
  labels:
    app: k8s-app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-app-demo
  template:
    metadata:
      labels:
        app: k8s-app-demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: k8s-app-demo
        image: silnux/k8s-app-demo:latest
        ports:
        - name: web
          containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 200Mi
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: k8s-app-demo
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: k8s-app-demo
  podMetricsEndpoints:
  - port: web
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: k8s-demo-app-rule
  namespace: default
spec:
  groups:
    # - name: http-requests-alert
    #   rules:
    #   - alert: HighHttpRequests
    #     expr: rate(http_requests_total{namespace!="", pod!=""}[2m]) > 0
    #     for: 2m
    #     labels:
    #       severity: warning
    #     annotations:
    #       summary: "High HTTP requests detected"
    #       description: "HTTP requests are above the threshold for more than 2 minutes."
    - name: http-requests-record
      rules:
      - record: job:http_requests_per_two_minutes:rate
        expr: rate(http_requests_total[2m]) by (job)

