apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: k8s-app-demo-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.100-192.168.0.200
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: k8s-app-demo-l2
  namespace: metallb-system