apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: k8s-app-demo
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: k8s-app-demo
  podMetricsEndpoints:
  - portNumber: 2025