apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: k8s-demo-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: k8s-demo-app
  podMetricsEndpoints:
  - port: web